document.addEventListener('DOMContentLoaded', () => {
    const fileInput = document.getElementById('csv-upload');
    const dashboardContent = document.getElementById('dashboard-content');
    const emptyState = document.getElementById('empty-state');
    
    let attentionChartInstance = null;
    let distractionsChartInstance = null;

    fileInput.addEventListener('change', (e) => {
        const file = e.target.files[0];
        if (!file) return;

        Papa.parse(file, {
            header: true,
            dynamicTyping: true,
            skipEmptyLines: true,
            complete: function(results) {
                processData(results.data);
            },
            error: function(error) {
                alert("Error parsing CSV: " + error.message);
            }
        });
    });

    function processData(data) {
        // Ensure data is valid timeseries
        if (!data || data.length === 0 || !('TimeOffset(s)' in data[0])) {
            alert("Invalid CSV format. Please upload a timeseries CSV generated by the application.");
            return;
        }

        // Process summary stats
        const totalRows = data.length;
        const avgAttention = data.reduce((acc, row) => acc + (row['Attention(%)'] || 0), 0) / totalRows;
        const finalDistractions = data[totalRows - 1]['Distractions'] || 0;
        
        // Calculate peak confusion
        const confCounts = { 'LOW': 0, 'MED': 0, 'HIGH': 0 };
        data.forEach(row => {
            if (row['Confusion'] && confCounts[row['Confusion']] !== undefined) {
                confCounts[row['Confusion']]++;
            }
        });
        const peakConfusion = Object.keys(confCounts).reduce((a, b) => confCounts[a] > confCounts[b] ? a : b);

        // Update UI
        document.getElementById('avg-attention').innerText = `${avgAttention.toFixed(1)}%`;
        document.getElementById('total-distractions').innerText = finalDistractions;
        document.getElementById('peak-confusion').innerText = peakConfusion;

        // Color coding for confusion state
        const confEl = document.getElementById('peak-confusion');
        if (peakConfusion === 'HIGH') confEl.style.color = '#ef4444';
        else if (peakConfusion === 'MED') confEl.style.color = '#f59e0b';
        else confEl.style.color = '#10b981';

        // Prepare chart data
        const labels = data.map(row => `${row['TimeOffset(s)']}s`);
        const attentionData = data.map(row => row['Attention(%)']);
        const distractionsData = data.map(row => row['Distractions']);

        renderCharts(labels, attentionData, distractionsData);

        // Show dashboard, hide empty state
        emptyState.classList.add('hidden');
        dashboardContent.classList.remove('hidden');
    }

    function renderCharts(labels, attentionData, distractionsData) {
        // Common chart styling for dark theme
        Chart.defaults.color = '#94a3b8';
        Chart.defaults.font.family = "'Inter', sans-serif";
        const gridColor = 'rgba(255, 255, 255, 0.05)';

        // 1. Attention Chart
        const ctxAtt = document.getElementById('attentionChart').getContext('2d');
        if (attentionChartInstance) attentionChartInstance.destroy();

        // Gradient for attention line
        const gradientAtt = ctxAtt.createLinearGradient(0, 0, 0, 400);
        gradientAtt.addColorStop(0, 'rgba(59, 130, 246, 0.5)');
        gradientAtt.addColorStop(1, 'rgba(59, 130, 246, 0.0)');

        attentionChartInstance = new Chart(ctxAtt, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Attention (%)',
                    data: attentionData,
                    borderColor: '#3b82f6',
                    backgroundColor: gradientAtt,
                    borderWidth: 2,
                    fill: true,
                    tension: 0.4,
                    pointRadius: 0,
                    pointHitRadius: 10
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        mode: 'index',
                        intersect: false,
                        backgroundColor: 'rgba(15, 23, 42, 0.9)',
                        titleColor: '#fff',
                        bodyColor: '#cbd5e1',
                        borderColor: 'rgba(255,255,255,0.1)',
                        borderWidth: 1
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        max: 100,
                        grid: { color: gridColor }
                    },
                    x: {
                        grid: { display: false }
                    }
                },
                interaction: {
                    mode: 'nearest',
                    axis: 'x',
                    intersect: false
                }
            }
        });

        // 2. Distractions Chart
        const ctxDist = document.getElementById('distractionsChart').getContext('2d');
        if (distractionsChartInstance) distractionsChartInstance.destroy();

        distractionsChartInstance = new Chart(ctxDist, {
            type: 'line',
            data: {
                labels: labels,
                datasets: [{
                    label: 'Cumulative Distractions',
                    data: distractionsData,
                    borderColor: '#8b5cf6',
                    backgroundColor: 'rgba(139, 92, 246, 0.1)',
                    borderWidth: 2,
                    fill: true,
                    stepped: true, // Good for cumulative counts
                    pointRadius: 0
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        mode: 'index',
                        intersect: false,
                        backgroundColor: 'rgba(15, 23, 42, 0.9)',
                        titleColor: '#fff',
                        bodyColor: '#cbd5e1',
                        borderColor: 'rgba(255,255,255,0.1)',
                        borderWidth: 1
                    }
                },
                scales: {
                    y: {
                        beginAtZero: true,
                        grid: { color: gridColor },
                        ticks: { stepSize: 1 }
                    },
                    x: {
                        grid: { display: false }
                    }
                }
            }
        });
    }
});
